src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\NotBlank]
    #[Assert\Email(message:'Vous devez saisir une adresse mail valide')]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[Assert\IsTrue(message:'Vous devez accepter les CGU')]
    #[ORM\Column]
    private ?bool $is_cgu_enabled = null;

        #[ORM\Column(type: 'boolean')]
private bool $isApiAccessEnabled = false;

    /**
     * @var Collection<int, Order>
     */
    #[ORM\OneToMany(targetEntity: Order::class, mappedBy: 'user', orphanRemoval: true)]

    private Collection $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function isCguEnabled(): ?bool
    {
        return $this->is_cgu_enabled;
    }

    public function setIsCguEnabled(bool $is_cgu_enabled): static
    {
        $this->is_cgu_enabled = $is_cgu_enabled;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): static
    {
        if ($this->orders->removeElement($order)) {
           
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;


    }




public function isApiAccessEnabled(): bool
{
    return $this->isApiAccessEnabled;
}

public function setIsApiAccessEnabled(bool $enabled): self
{
    $this->isApiAccessEnabled = $enabled;
    return $this;
}

}

src/Controller/HomeController.php
<?php

// src/Controller/HomeController.php

namespace App\Controller;


use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(ProductRepository $productRepository): Response
    {
        $products = $productRepository->findBy([], ['id' => 'DESC'], 9); 

        return $this->render('home/index.html.twig', [
            'products' => $products,
        ]);
    }
}

templates/home/index.html.twig
{# templates/home/index.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Accueil - GreenGoodies{% endblock %}

{% block body %}
    <section class="hero">
        <div class="leftHeroBlock">
            <div class="textHero">
                {% if app.user %}
    <h1>Bienvenue {{ app.user.firstName }}</h1>
{% else %}
    <h1>Bienvenue chez GreenGoodies</h1>
{% endif %}

                <p>Découvrez notre univers de produits durables et éthiques pour une consommation responsable.</p>
                <p>Retrouvez des articles d'hygiène & beauté, des accessoires & boissons et du prêt à porter</p>
            </div>
        </div>
        <div class="rightHeroBlock">
            <img src="images/hero.png" alt="Image d'accueil'">
        </div>
    </section>

    <section class="homeProducts">
        <h2>NOS PRODUITS</h2>
        <div class="productGrid">
            {% for product in products %}
                <div class="productCard home">
                    <div class="imgProduct">
                        <img src="{{ asset('uploads/products/' ~ product.picture) }}" alt="{{ product.name }}">
                    </div>
                    <div class="textProduct">
                        <h3>{{ product.name }}</h3>
                        <p class="shortDescription">{{product.shortDescription}}</p>
                        <p class="price">{{ product.price }} €</p>
                        <a class="linkProduct" href="{{path('app_product', {'id': product.id})}}">Voir le produit</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        
    </section>
    <section class="banner">
        <div class="bannerBlock">
            
            <div class="textBannerBlock">
                <h2>NOTRE CONVICTION</h2>
                <p>Chez GreenGoodies, nous croyons en un monde où le commerce peut être synonyme de bien-être pour la planète et ses habitants. Notre misssion est de vous proposer une sélection rigoureuse de produits qui allient qualité, durabilité et éthique.</p>
            </div>
            
            <img src="images/Login.png" alt="Bannières fleurs">

        </div>

        <div class="bannerBlock">
            
            <img src="images/plasticBag.png" alt="Bannières poubelles">
            
            <div class="textBannerBlock">
                <h2>NOS VALEURS</h2>
                <p>Durabilité : Nous sélectionnons soigneusement des produits qui respectent l'environnement et favorisent la durabilité.<br>
                Ethique : Nous nous engageons à travailler avec des partenaires et des fournisseurs qui partagent nos valeurs éthiques.<br>
                Ecologie : Nous encourageons des pratiques respectueuses de l'écosystème et privilégions les matériaux écologiques.'
                '</p>
            </div>
            
        </div>
    </section>
{% endblock %}